version: '3'
services:
  web:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Path to your custom FastAPI Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    depends_on:
      - db
    networks:
      - fastapi-app
    stdin_open: true
    volumes:
      - ./:/app
  db:
    image: postgres:13
    container_name: postgres-database
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=demo_db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
networks:
  fastapi-app:
    name: fastapi-app
    driver: bridge
