"""renamed

Revision ID: 4dbdb7517fa3
Revises: 1a5d6b5aaae4
Create Date: 2023-11-02 18:46:37.768490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dbdb7517fa3'
down_revision: Union[str, None] = '1a5d6b5aaae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_name'), 'User', ['name'], unique=False)
    op.create_index(op.f('ix_User_surname'), 'User', ['surname'], unique=False)
    op.create_table('Org',
    sa.Column('dummy_user_id', sa.String(length=32), nullable=True),
    sa.Column('org_name', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dummy_user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Org_dummy_user_id'), 'Org', ['dummy_user_id'], unique=False)
    op.create_index(op.f('ix_Org_org_name'), 'Org', ['org_name'], unique=False)
    op.drop_index('ix_DummyUser_name', table_name='DummyUser')
    op.drop_index('ix_DummyUser_surname', table_name='DummyUser')
    op.drop_table('DummyUser')
    op.drop_index('ix_DummyOrg_dummy_user_id', table_name='DummyOrg')
    op.drop_index('ix_DummyOrg_org_name', table_name='DummyOrg')
    op.drop_table('DummyOrg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DummyOrg',
    sa.Column('org_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('dummy_user_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dummy_user_id'], ['DummyUser.id'], name='DummyOrg_dummy_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='DummyOrg_pkey')
    )
    op.create_index('ix_DummyOrg_org_name', 'DummyOrg', ['org_name'], unique=False)
    op.create_index('ix_DummyOrg_dummy_user_id', 'DummyOrg', ['dummy_user_id'], unique=False)
    op.create_table('DummyUser',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='DummyUser_pkey')
    )
    op.create_index('ix_DummyUser_surname', 'DummyUser', ['surname'], unique=False)
    op.create_index('ix_DummyUser_name', 'DummyUser', ['name'], unique=False)
    op.drop_index(op.f('ix_Org_org_name'), table_name='Org')
    op.drop_index(op.f('ix_Org_dummy_user_id'), table_name='Org')
    op.drop_table('Org')
    op.drop_index(op.f('ix_User_surname'), table_name='User')
    op.drop_index(op.f('ix_User_name'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
