"""Tables Added

Revision ID: b0fe48885a4a
Revises: 
Create Date: 2023-11-02 15:58:14.506417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0fe48885a4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DummyOrg',
    sa.Column('org_name', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DummyOrg_org_name'), 'DummyOrg', ['org_name'], unique=False)
    op.create_table('DummyUser',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DummyUser_name'), 'DummyUser', ['name'], unique=False)
    op.create_index(op.f('ix_DummyUser_surname'), 'DummyUser', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DummyUser_surname'), table_name='DummyUser')
    op.drop_index(op.f('ix_DummyUser_name'), table_name='DummyUser')
    op.drop_table('DummyUser')
    op.drop_index(op.f('ix_DummyOrg_org_name'), table_name='DummyOrg')
    op.drop_table('DummyOrg')
    # ### end Alembic commands ###
