"""new field addition

Revision ID: fd439f7ef4b9
Revises: d5d55d6fe50b
Create Date: 2023-10-19 12:41:58.277863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd439f7ef4b9'
down_revision: Union[str, None] = 'd5d55d6fe50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dummyuser', sa.Column('dummy_surname', sa.String(), nullable=True))
    op.create_index(op.f('ix_dummyuser_dummy_surname'), 'dummyuser', ['dummy_surname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dummyuser_dummy_surname'), table_name='dummyuser')
    op.drop_column('dummyuser', 'dummy_surname')
    # ### end Alembic commands ###
